const jsonServer = require("json-server");
const server = jsonServer.create();
const router = jsonServer.router("db.json");
const middlewares = jsonServer.defaults();
const faker = require("faker");

const allPokemon = [
  "Dragonite",
  "Dragonair",
  "Snorlax",
  "Kabutops",
  "Omastar",
  "Flareon",
  "Jolteon",
  "Vaporeon",
  "Gyarados",
  "Magmar",
  "Electabuzz",
  "Jynx",
  "Mr-mime",
  "Starmie",
  "Seaking",
  "Seadra",
  "Chansey",
  "Rhydon",
  "Weezing",
  "Hitmonchan",
  "Hitmonlee",
  "Marowak",
  "Exeggutor",
  "Electrode",
  "Kingler",
  "Hypno",
  "Gengar",
  "Haunter",
  "Cloyster",
  "Muk",
  "Dewgong",
  "Dodrio",
  "Magneton",
  "Slowbro",
  "Rapidash",
  "Golem",
  "Graveler",
  "Tentacruel",
  "Victreebel",
  "Weepinbell",
  "Machamp",
  "Machoke",
  "Alakazam",
  "Kadabra",
  "Poliwrath",
  "Poliwhirl",
  "Arcanine",
  "Primeape",
  "Golduck",
  "Persian",
  "Dugtrio",
  "Venomoth",
  "Parasect",
  "Vileplume",
  "Gloom",
  "Golbat",
  "Wigglytuff",
  "Jigglypuff",
  "Ninetales",
  "Clefable",
  "Clefairy",
  "Nidoking",
  "Nidorino",
  "Nidoqueen",
  "Nidorina",
  "Sandslash",
  "Raichu",
  "Pikachu",
  "Arbok",
  "Fearow",
  "Raticate",
  "Pidgeot",
  "Pidgeotto",
  "Beedrill",
  "Kakuna",
  "Butterfree",
  "Metapod",
  "Blastoise",
  "Wartortle",
  "Charizard",
  "Charmeleon",
  "Venusaur",
  "Ivysaur",
  "Mew",
  "Mewtwo",
  "Dratini",
  "Moltres",
  "Zapdos",
  "Articuno",
  "Aerodactyl",
  "Kabuto",
  "Omanyte",
  "Porygon",
  "Eevee",
  "Ditto",
  "Lapras",
  "Magikarp",
  "Tauros",
  "Pinsir",
  "Scyther",
  "Staryu",
  "Goldeen",
  "Horsea",
  "Kangaskhan",
  "Tangela",
  "Rhyhorn",
  "Koffing",
  "Lickitung",
  "Cubone",
  "Exeggcute",
  "Voltorb",
  "Krabby",
  "Drowzee",
  "Onix",
  "Gastly",
  "Shellder",
  "Grimer",
  "Seel",
  "Doduo",
  "Farfetchd",
  "Magnemite",
  "Slowpoke",
  "Ponyta",
  "Geodude",
  "Tentacool",
  "Bellsprout",
  "Machop",
  "Abra",
  "Poliwag",
  "Growlithe",
  "Mankey",
  "Psyduck",
  "Meowth",
  "Diglett",
  "Venonat",
  "Paras",
  "Oddish",
  "Zubat",
  "Vulpix",
  "Nidoran-m",
  "Nidoran-f",
  "Sandshrew",
  "Ekans",
  "Spearow",
  "Rattata",
  "Pidgey",
  "Weedle",
  "Caterpie",
  "Squirtle",
  "Charmander",
  "Bulbasaur"
];

const randomName = () => faker.name.firstName();
const randomSpecies = () =>
  allPokemon[Math.floor(Math.random() * allPokemon.length)];

server.use(middlewares);

server.use(jsonServer.bodyParser);
server.use((req, res, next) => {
  if (req.method === "POST" && req.originalUrl === "/pokemons") {
    req.body.nickname = randomName();
    req.body.species = randomSpecies();
  } else if (req.method === "GET" && req.originalUrl === "/trainers") {
    req.query = { _embed: "pokemons" };
  }
  // Continue to JSON Server router
  next();
});

server.use(router);
server.listen(3000, () => {
  console.log("JSON Server is running");
});
